import {Poppins} from "next/font/google";
import Header from "./header/header"
import "../styles/globals.css"
export const metadata = {
  title: 'Issiz elan sayti',
  description: 'Generated by Next.js',
}

const poppins=Poppins({
  weight: ['400'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',//sehve yuklenenden sonra yuklensin font
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
